from train.loaders.load_model_architecture import LoadModelArchitectureStrategy
from train.loaders.load_trained_model import LoadTrainedModelStrategy
from train.loaders.load_dataset import LoadDatasetStrategy